import './bootstrap';
export { ContractName } from './domain/shared/value-objects/ContractName';
export { VariantType } from './domain/shared/value-objects/VariantType';
export { Variant } from './domain/variant/entities/Variant';
export type { ContractDomainEvent, ContractCreatedEvent, ContractValidatedEvent, VariantCreatedEvent, PropSchemaCreatedEvent } from './domain/shared/events/DomainEvent';
export type { IVariantFactory } from './domain/variant/services/VariantFactory';
export type { ICreateVariantUseCase } from './application/use-cases/CreateVariantUseCase';
export { CreateVariantUseCaseImpl } from './application/use-cases/CreateVariantUseCase';
export type { IVariantRepository } from './infrastructure/repositories/VariantRepository';
export type { ContractCategory, ContractDefinition, PropSchema, ChildrenRules, AccessibilityRules, UiVariantSize, UiVariantIntent, UiVariantTone, UiVariantEmphasis, UiA11yRole, UiA11yKeyboardAction, ContractProps, ContractEvents } from './types';
export declare const uiSizes: readonly string[];
export declare const uiIntents: readonly string[];
export declare const uiTones: readonly string[];
export declare const uiEmphases: readonly string[];
export declare const uiA11yRoles: readonly string[];
export declare const uiA11yKeyboardActions: readonly string[];
import { getContractCoreService } from './bootstrap';
export { getContractCoreService };
export declare function getStandardVariants(): any;
//# sourceMappingURL=index.d.ts.map