// src/validator/types.ts
// Error codes
export const VALIDATION_ERROR_CODES = {
    // Structure errors
    PATH_NOT_FOUND: 'PATH_NOT_FOUND',
    MISSING_REQUIRED_FILE: 'MISSING_REQUIRED_FILE',
    NO_TYPESCRIPT_FILES: 'NO_TYPESCRIPT_FILES',
    // Package errors
    MISSING_PACKAGE_NAME: 'MISSING_PACKAGE_NAME',
    INVALID_PACKAGE_NAME: 'INVALID_PACKAGE_NAME',
    MISSING_CORE_DEPENDENCY: 'MISSING_CORE_DEPENDENCY',
    INVALID_PACKAGE_JSON: 'INVALID_PACKAGE_JSON',
    // TypeScript errors
    FILE_READ_ERROR: 'FILE_READ_ERROR',
    NO_EXPORTS: 'NO_EXPORTS',
    // Export errors
    INDEX_READ_ERROR: 'INDEX_READ_ERROR',
    // Documentation errors
    MISSING_README: 'MISSING_README',
    MISSING_README_SECTION: 'MISSING_README_SECTION',
    README_READ_ERROR: 'README_READ_ERROR',
    // General errors
    VALIDATION_FAILED: 'VALIDATION_FAILED'
};
export const VALIDATION_WARNING_CODES = {
    // Structure warnings
    MISSING_RECOMMENDED_FILE: 'MISSING_RECOMMENDED_FILE',
    // Package warnings
    MISSING_TYPESCRIPT_DEV_DEP: 'MISSING_TYPESCRIPT_DEV_DEP',
    // TypeScript warnings
    MISSING_SEMANTIC_TYPE: 'MISSING_SEMANTIC_TYPE',
    // Export warnings
    NO_BARREL_EXPORTS: 'NO_BARREL_EXPORTS',
    NO_CORE_REEXPORTS: 'NO_CORE_REEXPORTS',
    // Documentation warnings
    NO_CODE_EXAMPLES: 'NO_CODE_EXAMPLES'
};
//# sourceMappingURL=types.js.map